name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
 deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e

            cd /var/services/docker_learning

            echo "Current commit:"
            git log --oneline -1

            git pull origin master

            echo "After pull:"
            git log --oneline -1

            docker compose down
            docker compose up --build -d

            docker image prune -f